#!/usr/bin/perl
## generates the two files (nodes.tsv and edges.tsv) needed for gephi visualization
##
## note the *edges.tsv file generated by generate_gephi_input_subproblems.pl can be reused for 
## visualizing the genomic features; the *nodes.tsv file needs to be regenerated (using this script)
## in order to highlight the centromere and teleomere regions
##
## argument 1: the normalized whole-genome contact map
##
## Kimberly MacKay Dec 4, 2017
## license: This work is licensed under the Creative Commons Attribution-NonCommercial-
## ShareAlike 3.0 Unported License. To view a copy of this license, visit 
## http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to Creative Commons, 
## PO Box 1866, Mountain View, CA 94042, USA.

use strict;
use warnings;

## check to ensure two arguments were passed in
die "ERROR: must pass in two arguments." if @ARGV != 2;

my $hic_file = $ARGV[0];
my $num_chr = $ARGV[1];

###########################################################################################
##	initialize some variables
###########################################################################################
## get the ending index of each chromosome
my @stop_index;
for(my $chr = 1; $chr <= $num_chr; $chr++)
{
	print STDERR "What is the ending index of CHR".$chr."? ";
	my $input = <STDIN>;
	$stop_index[$chr] = int($input);
}

	$stop_index[0] = 0;

###########################################################################################
##	identify centromere and telomere regions and print the file
###########################################################################################

## print the header line
print "id \t label \t chromosome\n";

## open the interaction matrix file
open WGCM, "$hic_file" or die "ERROR: $hic_file could not be opened.";
chomp(my @hic_matrix = <WGCM>);
close WGCM;

## loop through the matrix to identify the centromer and telomere regions
## for each line after the header line
for(my $row = 1; $row <= $#hic_matrix; $row++)
{
	## initialize a boolean flag
	my $nuclear_DNA = 0;

	## split the line
	my @matrix_line = split /\t/, $hic_matrix[$row];
	
	## loop through the entire file
	for(my $col = 1; $col <= $#hic_matrix; $col++)
	{
		## if the cell does not contain a "NA"
		if(!($matrix_line[$col] =~ "NA"))
		{
			$nuclear_DNA = 1;
		}
	}
	
	## if the matrix line contained nuclear DNA
	if($nuclear_DNA)
	{
		## print the appropriate line
		print $row."\tbin".$row."\tnuclear_DNA\n";
	}
	else
	{
		## else it is a centromere or telomere
		## print the appropriate line
		print $row."\tbin".$row."\tcentromere telomere\n";
	}
}